### ISSUE TITLE
Система отложенных сообщений

### ISSUE THREAD

**Issue by Pilik** [bvn13/JIrcBot#1]
Реализовать:
Пишем на канал с ботом:
-tell <ник пользователя> <сообщение>
Бот отвечает что "Сообщение записано".
Когда человек приходит на канал и пишет любое сообщение, бот выдаёт ему фразу оставленную пользователем в формате:
<highligth><nickname user> сказал <date>: <сообщение>.

Опционально:
- работа скрипта только на заданных каналах, включение выключение скрипта.
- ведение списка пользователей на канале для случая если пользователь никогда не заходил на канал, то в создании сообщения будет отказано. 
- ограничение срока хранения сообщений для пользователя

**Comment by bvn13** [comment]
Сделано.

Синтаксис:
```
?tell <username|me> your phrase here
```
Сообщение сохраняется в БД.
Когда собеседник с указанным ником напишет сообщение, то бот ему ответит:
```
bvn13: User bvn13 at 2018-02-01 11:45:05 told you: your phrase here
```
